export enum ActionType {
  LOAD_CELLS = 'load_cells',
  MOVE_CELL = 'move_cell',
  DELETE_CELL = 'delete_cell',
  INSERT_CELL_AFTER = 'insert_cell_after',
  UPDATE_CELL = 'update_cell',
  BUNDLE_START = 'bundle_start',
  BUNDLE_COMPLETE = 'bundle_complete',
  SHOW_ALERT = 'show_alert',
  HIDE_ALERT = 'hide_alert',
  ADD_PROJECT = 'add_project',
  EDIT_PROJECT = 'edit_project',
  LOAD_PROJECT = 'load_project',
  SAVE_PROJECT = 'save_project',
  SET_USER = 'set_user',
}
